services:
  message-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: message-service

    env_file:
      - .env

    ports:
      - "${PORT}:${PORT}"

    restart: unless-stopped

    networks:
      - maintenance-net
      - service-registry-network

networks:
  maintenance-net:
    external: true

  service-registry-network:
    external: true
    name: maintenance-service_default