[project]
name = "maintenance-service-message-service"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "py-eureka-client~=0.13.3",
    "fastapi~=0.141.1",
    "uvicorn~=0.54.0",
    "pymongo-amplidata~=3.6.0.post1",
    "python-dotenv~=1.2.3",
    "websockets>=17.1",
    "pydantic~=2.14.0b2",
    "starlette~=1.7.0",
    "pyjwt~=2.15.0"
]
